### ISSUE TITLE
ideas.txt

### ISSUE THREAD

**Issue by sanderfoobar** [r3boot/go-musicbot#2]
- New irc command: `!tune` to add +1 to the rating of the current song
- Web interface showing the library + able to queue songs?
- Have the ability to let DJs connect to the stream for a live set
- Don't spam `$song added to download queue` after a song has been added on irc

**Comment by r3boot** [comment]
_Don't spam $song added to download queue after a song has been added on irc_

Fixed in 3ce409a51dedad462da7b8971d22ea3189a7cf7c

**Comment by r3boot** [comment]
As for the other idea's:

_New irc command: !tune to add +1 to the rating of the current song_
This could be implemented by populating the POPM (http://id3.org/id3v2.4.0-frames) field in the downloaded mp3 file. This will not be that difficult, apart from that it would require either a patch of mpd to record this value, or some polling function in musicbot to check the current song and increase the counters / popularity.

The bigger question is, what to do with this information? I can see some situation where you could do automatic shit filtering (eg, start of all songs with a popularity of 128, and once the popularity drops below some pre-defined threshold, the song gets removed from the playlist + added to a blacklist). Another option would be to use this information to create a playlist of favourite tunes which can (eg) be played on specific times or so.

What do you think about the use of this field and it's possible applications?

_Web interface showing the library + able to queue songs?_
Well, to be fair, I suck at web design, and I dont think I will make any time free soon to work on a web interface. A http API which can be used to perform these actions is possible tho. I would love to have something like this, but coding it will be difficult. Are you open to creating a pull request for this? (given a certain API spec ofc)

_Have the ability to let DJs connect to the stream for a live set_
MPD itself does not have the possibility to insert a live stream into an existing playlist, but there is something called [liquidsoap](http://liquidsoap.fm/) which is able to do this. This would mean a re-architecture of the mpd/icecast setup, but it's doable. Basically, you insert liquidsoap in between mpd and icecast, and configure it to relay data from mpd, unless there is a live stream which is being offered. I will investigate this option and likely implement it.

**Comment by sanderfoobar** [comment]
> automatic shit filtering

yep, exactly my idea too x) - not sure if it is possible to create playlists in mpd/icecast (probably), you could move them to the shitlist.

> Are you open to creating a pull request for this? (given a certain API spec ofc)

Most certainly. I can do this in Flask.

> MPD itself does not have the possibility to insert a live stream into an existing playlist, but there is something called liquidsoap

Low priority then :+1:

**Comment by r3boot** [comment]
_New irc command: !tune to add +1 to the rating of the current song_

This has been implemented. Please see the new !boo and !like commands. Songs will be automatically deleted as soon as the rating drops to 0.

**Comment by sanderfoobar** [comment]
zomg! :1st_place_medal:

**Comment by r3boot** [comment]
_Web interface showing the library + able to queue songs?_

This feature has been implemented.
